import os

base = r"e:\gestion scolaire\gestion_scolaire_landshape"

dirs = [
    "app",
    "app/models",
    "app/blueprints",
    "app/blueprints/auth",
    "app/blueprints/public",
    "app/blueprints/admin",
    "app/blueprints/professeur",
    "app/blueprints/etudiant",
    "app/blueprints/parent",
    "app/blueprints/api",
    "app/services",
    "app/sockets",
    "app/utils",
    "app/templates",
    "app/templates/auth",
    "app/templates/public",
    "app/templates/admin",
    "app/templates/professeur",
    "app/templates/etudiant",
    "app/templates/parent",
    "app/static",
    "app/static/css",
    "app/static/js",
    "app/static/img",
    "app/static/uploads",
    "app/static/uploads/cours",
    "app/static/uploads/devoirs",
    "app/static/uploads/soumissions",
    "app/static/uploads/corrections",
    "app/static/uploads/justifications",
    "app/static/uploads/releves",
    "migrations"
]

files = [
    "run.py",
    "config.py",
    ".env",
    "requirements.txt",
    "app/__init__.py",
    "app/extensions.py",
    "app/models/__init__.py",
    "app/models/user.py",
    "app/models/academic.py",
    "app/models/profiles.py",
    "app/models/program.py",
    "app/models/evaluation.py",
    "app/models/presence.py",
    "app/models/communication.py",
    "app/models/pedagogy.py",
    "app/models/planning.py",
    "app/models/posts.py",
    "app/models/audit.py",
    "app/blueprints/auth/__init__.py",
    "app/blueprints/auth/routes.py",
    "app/blueprints/public/__init__.py",
    "app/blueprints/public/routes.py",
    "app/blueprints/admin/__init__.py",
    "app/blueprints/admin/routes.py",
    "app/blueprints/professeur/__init__.py",
    "app/blueprints/professeur/routes.py",
    "app/blueprints/etudiant/__init__.py",
    "app/blueprints/etudiant/routes.py",
    "app/blueprints/parent/__init__.py",
    "app/blueprints/parent/routes.py",
    "app/blueprints/api/__init__.py",
    "app/blueprints/api/routes.py",
    "app/services/auth_service.py",
    "app/services/note_service.py",
    "app/services/presence_service.py",
    "app/services/pdf_service.py",
    "app/services/qr_service.py",
    "app/services/notif_service.py",
    "app/services/mail_service.py",
    "app/sockets/__init__.py",
    "app/sockets/chat.py",
    "app/sockets/notifications.py",
    "app/utils/decorators.py",
    "app/utils/helpers.py",
    "app/utils/validators.py",
    "app/templates/base.html",
    "app/templates/base_admin.html",
    "app/templates/base_dashboard.html",
    "app/templates/auth/login.html",
    "app/templates/public/home.html",
    "app/templates/public/emploi_temps.html",
    "app/templates/public/examens.html",
    "app/templates/public/annonces.html",
    "app/templates/public/cours_public.html",
    "app/templates/admin/dashboard.html",
    "app/templates/admin/etudiants.html",
    "app/templates/admin/professeurs.html",
    "app/templates/admin/specialites_matieres.html",
    "app/templates/admin/emploi_temps.html",
    "app/templates/admin/examens.html",
    "app/templates/admin/annonces.html",
    "app/templates/admin/justifications.html",
    "app/templates/professeur/dashboard.html",
    "app/templates/professeur/notes.html",
    "app/templates/professeur/presences.html",
    "app/templates/professeur/cours.html",
    "app/templates/professeur/devoirs.html",
    "app/templates/professeur/corrections.html",
    "app/templates/professeur/chat.html",
    "app/templates/professeur/posts.html",
    "app/templates/etudiant/dashboard.html",
    "app/templates/etudiant/notes_bulletin.html",
    "app/templates/etudiant/espace_cours.html",
    "app/templates/etudiant/chat.html",
    "app/templates/etudiant/releve.html",
    "app/templates/parent/dashboard.html",
    "app/templates/parent/absences.html",
    "app/templates/parent/releve.html",
    "app/templates/parent/chat.html",
    "app/static/css/edunova.css",
    "app/static/js/background.js",
    "app/static/js/i18n.js",
    "app/static/js/chat.js",
    "app/static/js/notifications.js",
    "app/static/img/logo.svg"
]

for d in dirs:
    os.makedirs(os.path.join(base, d), exist_ok=True)

for f in files:
    open(os.path.join(base, f), 'a').close()

print("Architecture created successfully!")
